# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd0162da4304efa0efd31588e2f21aaa7e77cba8e39cf3132383e4efa2368ea264e831ba4e810a0fe444716f4a93967d597051de773041708cd6a3a9ee79e2c

test:
  secret_key_base: 02c54d0d13ba6628a74b6b81ff89a73018e0e91aa3f45534d54957f9f2e79aaadc286ddf28ad0b477f8b2b41c2aeb4501297f63596e40d3d9b78c0a960559455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
